// examples/vue/src/App.vue
<template>
  <div id="app">
    <p>
      <img alt="Vue logo" src="./assets/logo.png" />
    </p>

    <strong>SDK demo for Vue.js</strong>

    <div class="row">
      <input type="text" placeholder="Project ID" v-model="projectId" />
      <button @click="loadMarkerSDK">Load SDK</button>
    </div>

    <div class="actions" v-if="loaded">
      <div class="panel">
        <button @click="widget.show">widget.show()</button>
        <button @click="widget.hide">widget.hide()</button>
        <button @click="() => widget.capture()">widget.capture()</button>
        <button @click="unloadMarkerSDK">widget.unload()</button>
      </div>

      <form class="form panel" @submit.prevent="updateReporterInfo">
        <label for="reporter-email">Email</label>
        <input id="reporter-email" type="email" required v-model="reporterInfo.email" />

        <label for="reporter-fullname">Full name</label>
        <input id="reporter-fullname" type="text" v-model="reporterInfo.fullName" />

        <button type="submit">widget.setReporter</button>
        <button @click="clearReporter">widget.clearReporter</button>
      </form>

      <form class="form panel" @submit.prevent="updateCustomData">
        <textarea class="code" v-model="customDataRaw" placeholder="Paste JSON"></textarea>

        <button type="submit">widget.setCustomData</button>

        <div class="error" v-if="customDataInvalid">Invalid JSON format</div>
      </form>

      <div class="form panel">
        <label for="event-log">Event log</label>
        <textarea id="event-log" readonly v-model="eventLog" class="event-log"></textarea>
      </div>
    </div>
  </div>
</template>

<script>
import markerSDK from '@marker.io/browser';

export default {
  name: 'App',

  data() {
    return {
      widget: null,

      // You can find your project ID in your Marker.io account.
      // Learn mode: https://github.com/marker-io/browser-sdk/tree/master/examples/vue#getting-your-project-id
      projectId: '',

      reporterInfo: {
        email: null,
        fullName: null,
      },

      eventLog: '',

      customDataRaw: '',
      customDataObject: {},
      customDataInvalid: false,
    };
  },

  methods: {
    async loadMarkerSDK() {
      // Load widget using the Marker.io SDK
      this.widget = await markerSDK.loadWidget({
        project: this.projectId,
      });

      const events = [
        'load',
        'loaderror',
        'beforeunload',
        'show',
        'hide',
        'capture',
        'feedbackbeforesend',
        'feedbacksent',
        'feedbackerror',
        'feedbackdiscarded',
      ];

      for (const eventName of events) {
        this.widget.on(eventName, () => {
          this.eventLog += `Event "${eventName}"\n`;
        });
      }
    },

    unloadMarkerSDK() {
      this.widget.unload();
      this.widget = null;
    },

    updateReporterInfo() {
      this.widget.setReporter(this.reporterInfo);
    },

    clearReporter() {
      this.widget.clearReporter();
    },

    updateCustomData() {
      try {
        this.customDataObject = JSON.parse(this.customDataRaw);
        this.customDataInvalid = false;
      } catch {
        this.customDataInvalid = true;
      }

      this.widget.setCustomData(this.customDataObject);
    },
  },

  computed: {
    loaded() {
      return !!this.widget;
    },
  },
};
</script>

<style lang="scss">
body {
  background: #edf2ff;
}

#app {
  font-family: sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  max-width: 400px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;

  * {
    box-sizing: border-box;
  }

  > * + * {
    margin-top: 20px;
  }
}

.row {
  display: flex;
  flex-direction: row;

  input {
    flex-grow: 1;
    height: 20px;
  }

  > * + * {
    margin-left: 10px;
  }
}

.actions {
  display: flex;
  flex-direction: column;

  > * + * {
    margin-top: 10px;
  }
}

.panel {
  border-radius: 6px;
  box-shadow: 0 2px 8px -3px #0006;
  background: white;
  padding: 15px;
  display: flex;
  flex-direction: column;

  > * + * {
    margin-top: 10px;
  }
}

.form {
  text-align: left;
  margin-top: 20px;

  label {
    font-weight: 600;
    font-size: 14px;
  }

  label + input {
    margin-top: 2px;
  }

  input + label {
    margin-top: 10px;
  }

  input + button {
    margin-top: 20px;
  }
}

.event-log {
  height: 300px;
}

.code {
  font-family: monospace;
}

.error {
  color: #f03e3e;
}
</style>

// examples/react/src/App.tsx
import reactLogo from './assets/react.svg';
import viteLogo from '/vite.svg';
import './App.css';
import { useMarkerIo } from './hooks/marker-io';
import { useState } from 'react';

function App() {
  const [reporterInfo, setReporterInfo] = useState({
    email: '',
    fullName: '',
  });

  const {
    loadMarkerSDK,
    loaded,
    widget,
    unloadMarkerSDK,
    eventLog,
    setProjectId,
    projectId,
    updateCustomData,
    updateReporterInfo,
    customDataRaw,
    setCustomDataRaw,
    customDataInvalid,
    clearReporter,
  } = useMarkerIo();

  return (
    <>
      <div id="app">
        <div className="">
          <strong>Maker io SDK demo for React and Vite</strong>
          <div>
            <a href="https://vitejs.dev" target="_blank">
              <img src={viteLogo} className="logo" alt="Vite logo" />
            </a>
            <a href="https://react.dev" target="_blank">
              <img src={reactLogo} className="logo react" alt="React logo" />
            </a>
          </div>
        </div>

        <div className="col">
          <input
            type="text"
            style={{ width: '100%', marginBottom: '1rem', padding: '0.5rem' }}
            placeholder="Project ID"
            value={projectId}
            onChange={(e) => setProjectId(e.target.value)}
          />
          <button onClick={() => void loadMarkerSDK()}>Load SDK</button>
        </div>

        {loaded && (
          <div className="actions">
            <div className="panel">
              <button onClick={() => widget?.show()}>widget.show()</button>
              <button onClick={() => widget?.hide()}>widget.hide()</button>
              <button onClick={() => void widget?.capture('fullscreen')}>widget.capture()</button>
              <button onClick={unloadMarkerSDK}>widget.unload()</button>
            </div>

            <form
              className="form panel"
              onSubmit={(e) => {
                e.preventDefault();

                updateReporterInfo({
                  email: reporterInfo.email,
                  fullName: reporterInfo.fullName,
                });
              }}
            >
              <label htmlFor="reporter-email">Email</label>
              <input
                id="reporter-email"
                type="email"
                required
                value={reporterInfo.email}
                onChange={(e) => setReporterInfo({ ...reporterInfo, email: e.target.value })}
              />

              <label htmlFor="reporter-fullname">Full name</label>
              <input
                id="reporter-fullname"
                type="text"
                value={reporterInfo.fullName}
                onChange={(e) => setReporterInfo({ ...reporterInfo, fullName: e.target.value })}
              />

              <button type="submit">widget.setReporter</button>
              <button onClick={clearReporter}>widget.clearReporter</button>
            </form>

            <form
              className="form panel"
              onSubmit={(e) => {
                e.preventDefault();
                updateCustomData();
              }}
            >
              <textarea
                className="code"
                value={customDataRaw}
                onChange={(e) => setCustomDataRaw(e.target.value)}
                placeholder="Paste JSON"
              ></textarea>

              <button type="submit">widget.setCustomData</button>

              {customDataInvalid && <div className="error">Invalid JSON format</div>}
            </form>

            <div className="form panel">
              <label htmlFor="event-log">Event log</label>
              <textarea id="event-log" readOnly value={eventLog} className="event-log"></textarea>
            </div>
          </div>
        )}
      </div>
    </>
  );
}

export default App;
